services:
  api:
    container_name: gb_test-api
    build: ./backend
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/gb_test
    ports:
      - 3000:3000
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3000
    networks:
      - network
    ports:
      - 5173:5173
    depends_on:
      - api

  postgres:
    container_name: gb_test-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gb_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gb_test"]
      start_interval: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
